version: '2.1'

services:
  postgres:
    container_name: "chat-postgres"
    build: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "chat"
      POSTGRES_PASSWORD: "mysecretpassword"
